[package]
name = "quasar-indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
config = "0.13.3"
log = "0.4.20"
log4rs = "1.2.0"
serde = { version = "1.0.188", features = ["derive"] }
