//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::{entity::prelude::*, ActiveValue, Set};
use stellar_xdr::{ContractEvent, Error};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub topic: String,
    pub contract_id: String,
    pub ledger: i32,
    pub value: Json,
    pub r#type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

impl TryFrom<ContractEvent> for ActiveModel {
    type Error = Error;

    fn try_from(event: ContractEvent) -> Result<Self, Self::Error> {
        // let topic = match event.body {
        //     stellar_xdr::ContractEventBody::V0(body) => {
        //         let data = body.data.discriminant()
        //         body.topics.into_iter().map(|topic| topic.name())
        //     }
        // };
        Ok(Self {
            id: ActiveValue::NotSet,
            topic: ActiveValue::NotSet,
            contract_id: Set(event.contract_id.unwrap().to_string()),
            ledger: ActiveValue::NotSet,
            value: ActiveValue::NotSet,
            r#type: Set(event.type_.to_string()),
        })
    }
}
