//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "accountdata")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub accountid: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub dataname: String,
    pub datavalue: String,
    pub lastmodified: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub extension: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub ledgerext: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
