//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ledgerheaders")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub ledgerhash: String,
    pub prevhash: String,
    pub bucketlisthash: String,
    #[sea_orm(unique)]
    pub ledgerseq: Option<i32>,
    pub closetime: i64,
    #[sea_orm(column_type = "Text")]
    pub data: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
