//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "offers")]
pub struct Model {
    pub sellerid: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub offerid: i64,
    #[sea_orm(column_type = "Text")]
    pub sellingasset: String,
    #[sea_orm(column_type = "Text")]
    pub buyingasset: String,
    pub amount: i64,
    pub pricen: i32,
    pub priced: i32,
    #[sea_orm(column_type = "Double")]
    pub price: f64,
    pub flags: i32,
    pub lastmodified: i32,
    #[sea_orm(column_type = "Text")]
    pub extension: String,
    #[sea_orm(column_type = "Text")]
    pub ledgerext: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
