name: Build

on:
  push:
    branches: ["main"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    timeout-minutes: 10
    permissions:
      contents: read
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: quasar
          POSTGRES_USER: quasar
          POSTGRES_PASSWORD: quasar

    env:
      DATABASE_URL: "postgres://quasar:quasar@localhost:5432/quasar"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.72.0
      - name: Check default features
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Check all features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
